name: Release version on tag

on:
  push:
    tags:
      - "*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Install dos2unix
        run: sudo apt-get update && sudo apt-get install -y dos2unix
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Make build script executable
        run: chmod +x ./build.sh
      - name: Test build package
        run: ./build.sh
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: "This release was created from tag ${{ github.ref_name }}."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/distributions/nixlper-${{ github.ref_name }}.tar
          asset_name: nixlper-${{ github.ref_name }}.tar
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
